// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awzoqqwcstmupfmlasvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3em9xcXdjc3RtdXBmbWxhc3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzExMDAsImV4cCI6MjA2MDk0NzEwMH0.sLEztv0e4nk_sbXmJZfDcx1Y58JFC-M7X-mwQcb0z3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);